### ISSUE TITLE
[DE] Error in translation "Hurenkinder und Schusterjungen"

### ISSUE THREAD

**Issue by EmnichtdaYT** [scribusproject/scribus-translations#13]
Uh so I recently stumbled across something here,
"Hurenkinder und Schusterjungen" in German does not mean "Orphans and Widows". It rather means "Whore's children and cobbler's boys" which is probably not what y'all meant.
~Zoe

**Comment by aoloe** [comment]
hi zoe

as much those terms might be shocking to you, i think that the german print world has not replaced them yet.

at least, the wikipedia page does not mention an established replacement:

https://de.wikipedia.org/wiki/Hurenkind_und_Schusterjunge

personally, i would be fine, if scribus would be using the "anglicisms"  _Witwe_ und  _Waisenkind_ mentioned by wikipedia.  
but, but the fact that they are not _good_ either, might be the reason why, they could not replace the traditional terms.

if you have a replacement that you think will be understood by german speaking users, you're welcome to make a request in the official bug tracker (https://bugs.scribus.net) with references to the usages (or promotion?) for those new terms.

ciao
a.l.e

**Comment by EmnichtdaYT** [comment]
Okay, weird. I didn't know about that. Most apps don't use this term tho.

**Comment by aoloe** [comment]
can you mention what terms other apps use?

if there are better ones, i'm all for using them.
