### ISSUE TITLE
Hungarian team

### ISSUE THREAD

**Issue by gyuris** [scribusproject/scribus-translations#3]
We, the [Hungarian team](https://www.transifex.com/scribus/teams/41672/hu/) decided to use Transifex. We no longer send patches to SVN.

Coordinator: Gyuris Gellért, Github: @gyuris, Transifex: [@bubu](https://www.transifex.com/user/profile/bubu/), mail: in the Scribus source

**Comment by luzpaz** [comment]
Thank @gyuris 
added you to list (c4593ee21e9eba92083cb4cf12fd903fc7fe0cdd)

re: transifex
I'm talking with Craig and we're working on a fix for teh Transifex -> Trunk workflow. Stay tuned :smile:
